export const ADD_CONTENT="ADD_CONTENT"
export const GET_CONTENTS="GET_CONTENTS"
export const UPDATE_CONTENT="UPDATE_CONTENT"
export const DELETE_CONTENT = "DELETE_CONTENT"
export const GET_CONTENT = "GET_CONTENT"

export const ADD_TO_READING = "ADD_TO_READING"
export const ADD_READING_COUNT="ADD_READING_COUNT"